# use 3.7 as docker compose version
version: "3.7"

# define each services
services:
  # define app service (node js) called item-app
  item-app:
    # use the specified docker image from github packages
    image: docker.pkg.github.com/nafifurqon/item-app/item-app:v1

    # map port 80 on the host to port 8080 in the container
    ports:
      - 80:8080

    # depend on the item-db service, ensuring it's launched first
    depends_on:
      - item-db

    # always restart the item-app service
    restart: always

  # define database service (mongo db) called item-db
  item-db:
    # use the specified docker image for MongoDB version 3
    image: mongo:3

    # mount the volume named app-db to /data/db in the container
    volumes:
      - app-db:/data/db

    # always restart the item-db service
    restart: always

# define volumes
volumes:
  # define a named volume called app-db
  app-db: